package br.com.diegoduarte.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName = "Usuario")
public class Usuario {

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	private String firstName;

	private String lastName;
}